name: music_playlist
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  spotify_sdk: ^3.0.2
  audioplayers: ^6.1.0
  http: ^1.2.2
  flutter_web_auth_2: ^4.1.0
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/music/
    - assets/image/
